### ISSUE TITLE
Documentation of Blender Case Study

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Case-Studies#1]
@js6450 and @jameshosken, you can now add your case study report to this repo. You can either make a markdown file here with all the info and links or just link outward from the schedule to wherever you do a write-up. What do you think?

**Comment by shiffman** [comment]
(FYI only @jameshosken is assigned at the moment I'll add @js6450 once you accept the org invite!)

**Comment by js6450** [comment]
Hi Dan,

We have a google doc, which we are going to convert into a markdown file
and add to the Case Study repo. We will link it to the schedule also.
ᐧ

**Comment by jameshosken** [comment]
Converting to markdown is very tedious so I've just linked (#2) to the gdocs for now.

**Comment by shiffman** [comment]
Could you also add a link in `README` to the markdown file?

**Comment by js6450** [comment]
Will do!
ᐧ

**Comment by shiffman** [comment]
This is complete, great work!
