### ISSUE TITLE
Sept 25 Presentation: Wordpress

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Case-Studies#11]
Opening an issue to confirm Wordpress as the Case Study topic for @muji786 and @vince19972 on  Sept 25. Plan to present in ~15 minutes for next week. Thank you!

**Comment by vince19972** [comment]
@shiffman we'll do Wordpress on Sep 25. And we'll keep it short and succinct!

**Comment by shiffman** [comment]
Thanks for the report! Closing as this is complete!
