### ISSUE TITLE
Oct 23 - OpenROV

### ISSUE THREAD

**Issue by marcelmouse** [Open-Source-Studio-at-ITP/Case-Studies#21]
@tinkrmind have any ideas for this?

not sure this is project worthy but i've been interested in the open-sourceness of this:
https://www.bellingcat.com
https://www.newyorker.com/culture/culture-desk/how-to-conduct-an-open-source-investigation-according-to-the-founder-of-bellingcat

**Comment by tinkrmind** [comment]
Seems interesting at a first glance. I was thinking of something in the opensource hardware space. Like [OpenROV](https://www.openrov.com/) or [LittleBits](https://littlebits.com/)(they're local). I have some contacts in the Open Source Hardware Association([OSHWA](https://www.oshwa.org/)) as well. So we can take a top-level view evaluating the organization that grants open source hardware license (which is itself an open source organization). Also, there have been some interesting developments in open hardware for security. 

(if you can't tell I really had my heart set on open source hardware 😛

**Comment by marcelmouse** [comment]
heh heh i'm down to cover open source hardware with you since i know next to nothing about it

i was just hanging with a friend that works at [critter & guitari](https://www.critterandguitari.com/organelle), a synthesizer company, and he mentioned that they are open-source (not really sure if its the actual hardware part that is OS or the just the software part)

**Comment by tinkrmind** [comment]
I'm down for any cool hardware company! I'm working on [Programmable-Air](github.com/tinkrmind/programmable-air) so I really want to understand how open hardware works as a business! 

At a first glance, it appears that the [Organelle](https://www.critterandguitari.com/organelle#resources) runs on open source software, but the hardware is proprietary.

**Comment by shiffman** [comment]
Thanks for the presentation! Great work.
