### ISSUE TITLE
October 16 Presentation: three.js

### ISSUE THREAD

**Issue by shiffman** [Open-Source-Studio-at-ITP/Case-Studies#23]
Adding an issue for discussion and tracking of @nicolaspe and @alicehgsun's Case Study report.

**Comment by alicehgsun** [comment]
[link to slides!](https://docs.google.com/presentation/d/12HrrSnFpWByxBHR5KuOA50zPJqWcw741pWt4ekSVAyk/edit?usp=sharing)

**Comment by shiffman** [comment]
Great! Can you pull request a link to this from the README?

**Comment by shiffman** [comment]
This is complete!
